---
title: "Chapter 6"
author: "Minho Shin"
date: '`r Sys.Date()`'
output: 
  html_document: 
    keep_md: true
    highlight_downlit: TRUE
    highlight: ../theme/themes/adam_one_light.theme
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  dpi = 300,
  fig.width = 7,
  cache = TRUE
  )
```

```{r load-library, warning=FALSE, message=FALSE}
library(here)
library(tidyverse)
library(brms)
options(mc.cores = 4)
options(brms.backend = "cmdstanr")
```

## Fitting a simple regression to fake data

```{r sim-fake-data}
x <- 1:20
n <- length(x)
a <- 0.2
b <- 0.3
sigma <- 0.5
y <- a + b*x + sigma*rnorm(n)
```

```{r fit-fake-data}
fake <- data.frame(x, y)
fit_1 <- brm(y ~ x, data=fake)
```

### Show fit results

```{r print-fit}
fit_1
plot(fit_1)
```

### Plot the data and fitted line

```{r plot-pred}
fake %>%
  modelr::data_grid(x = modelr::seq_range(x, n = 20)) %>%
  tidybayes::add_epred_draws(fit_1, ndraws = 100) %>%   # sample 100 means from the posterior
  ggplot(aes(x = x, y = y)) +
  geom_point(data = fake) +
  geom_line(aes(x = x, y = .epred, group = .draw), alpha = .2) +
  labs(
    x = "Fake x",
    y = "Fake y"
  ) +
  bayesplot::theme_default()
```

